[tool.poetry]
authors = ["Philip Delorenzo <git@deloarts.com>"]
classifiers = ["Operating System :: Windows"]
description = "A wrapper for the catia v5 api."
name = "pytia"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
click = "8.1.3"
colorama = "0.4.4"
psutil = "5.9.0"
python = "^3.10"
pywin32 = "304"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pdoc3 = "^0.10.0"
pre-commit = "^2.19.0"
pylint = "^2.13.9"
pytest = "^7.1.1"
setuptools = "^62.3.1"
validators = "^0.19.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
