"""
    Module that hold all constants for pytia.
"""

import os

from pytia import __version__

LOG_FILENAME = "pytia.log"

PROP_NAME = "pytia"
PROP_VERSION = f"{PROP_NAME}.version"

HOSTNAME = str(os.environ.get("COMPUTERNAME"))
USERNAME = str(os.environ.get("USERNAME"))
USERPROFILE = str(os.environ.get("USERPROFILE"))
APPDATA = str(os.environ.get("APPDATA")) + "\\pytia"

CONSOLE_GREY = "\033[1;30m"
CONSOLE_YELLOW = "\033[93m"
CONSOLE_RED = "\033[91m"
CONSOLE_GREEN = "\033[92m"
CONSOLE_RESET = "\033[0m"

CONSOLE_HEADER = f"{CONSOLE_YELLOW}\nPYTIA {__version__}{CONSOLE_RESET}\n"
CONSOLE_STATUS_FAIL = f"{CONSOLE_RED}[ FAIL ]{CONSOLE_RESET}"
CONSOLE_STATUS_WARN = f"{CONSOLE_YELLOW}[ WARN ]{CONSOLE_RESET}"
CONSOLE_STATUS_INFO = f"{CONSOLE_GREY}[ INFO ]{CONSOLE_RESET}"
CONSOLE_STATUS_OK = f"{CONSOLE_GREEN}[  OK  ]{CONSOLE_RESET}"

ENV_NO_PROPS = os.environ.get("PYTIA_NO_PROPS")
ENV_IGNORE_BOM_ERROR = os.environ.get("PYTIA_IGNORE_BOM_ERROR")

GET_ITEM_BILL_OF_MATERIAL = "BillOfMaterial"
GET_ITEM_LISTING_REPORT = "ListingReport"
GET_ITEM_MATERIAL_MANAGER = "CATMatManagerVBExt"

KNOWN_ERRORS = ["-2147467259"]

FILE_EXTENSION_PART = "CATPart"
FILE_EXTENSION_PRODUCT = "CATProduct"
FILE_EXTENSION_DRAWING = "CATDrawing"
FILE_EXTENSION_MATERIAL = "CATMaterial"
VALID_FILE_EXTENSIONS = [
    FILE_EXTENSION_PART,
    FILE_EXTENSION_PRODUCT,
    FILE_EXTENSION_DRAWING,
    FILE_EXTENSION_MATERIAL,
]

FOREGROUND_VIEW = 1
BACKGROUND_VIEW = 2
